### ISSUE TITLE
Make the buttons work on the phone

### ISSUE THREAD

**Issue by errai34** [UniverseTBD/universeTBD.github.io#34]
For some reason, we cannot get to the Product, Research, etc. from the phone. I wonder if this would be a hard fix.

**Comment by jayden626** [comment]
As far as I can tell, Bootstrap isn't working / wasn't imported correctly. I'm not entirely sure, but including `import 'bootstrap'` in the `NavbarDefault.vue` file fixes this. Made a few other small improvements as well

![image](https://github.com/UniverseTBD/universeTBD.github.io/assets/22155312/039c9d08-d69b-4d57-a44e-356982a3f6ec)
