### ISSUE TITLE
Update the member list to include the new members

### ISSUE THREAD

**Issue by errai34** [UniverseTBD/universeTBD.github.io#35]
* Gabi, Rish, Mike W, Rohit, Manika, Maciej, Simone, Marc to send pic and description to #website, Jesse or Huiling
*  website to be updated accordingly
*  would it be possibly to have a circle with all of us, rather than a list?

**Comment by jcranney** [comment]
I haven't seen pics or bios yet for these peeps, are they available somewhere?

**Comment by errai34** [comment]
We will put everyone here: https://drive.google.com/drive/folders/1cmJUiS5hLOXp9W-QPXyxr2g3ifiB4VKa?usp=sharing

**Comment by jcranney** [comment]
Closing because now we have a pipeline for adding people via the google doc :)
