### ISSUE TITLE
Update Membership application for new members in Join Us

### ISSUE THREAD

**Issue by errai34** [UniverseTBD/universeTBD.github.io#38]
https://docs.google.com/forms/d/e/1FAIpQLSfvLGSjlggq42ODXq3Z-zWJsH095hQs5mvtSsgJqGEBiU5Iew/viewform 

@sandorkruk @kartheikiyer let's finalise a new membership policy

**Comment by jcranney** [comment]
This membership form has been superseded by the discord link for now. Closing this issue.
