### ISSUE TITLE
Typist effect breaks when navigating website

### ISSUE THREAD

**Issue by jayden626** [UniverseTBD/universeTBD.github.io#44]
The "Typist" animation breaks badly when navigating around the page. Should be looked into.
[Screencast_20240519_182903.webm](https://github.com/UniverseTBD/universeTBD.github.io/assets/22155312/a0a8497a-0b1e-4776-a44f-ab5c3cadb962)

**Comment by jcranney** [comment]
@jayden626 can you check out the live version of the website now to see if it's still broken? I've removed the effect from everywhere except the home page because I think multiple pages were trying to handle the effect as you navigate around the website.

**Comment by errai34** [comment]
still broken :-( it's cute but a pain to handle :D

**Comment by jcranney** [comment]
@errai34 @jayden626  have you noticed if the "counting" numbers on the front page are buggy, or is it just the typed effect of the "UniverseTBD"? I think it might just be the typed effect so we can keep the counters for "500,000" papers etc

**Comment by errai34** [comment]
yeah, it's just for UTBD, it's a pity cos they go together with the numbers. Would it be possible to stop the typist effect for now, just to keep things relatively stable?

**Comment by jcranney** [comment]
done! looks good with just the numbers anyway :)
