### ISSUE TITLE
Credit Ze-chang for the website as the creator and designer

### ISSUE THREAD

**Issue by errai34** [UniverseTBD/universeTBD.github.io#50]
Hi Infra, can we update the About Us section to publicly credit Zechang (Ze-chang Sun, Tsinghua University) as the creator and designer of the website, maybe in the About Us section somewhere in the first few paragraphs, where it fits best? He's made us the beauty we are now using.Thank you!! (

**Comment by jcranney** [comment]
I think it looks nice in bold at the bottom of the About Us page. What do you think?

![image](https://github.com/user-attachments/assets/e826a8e2-61d8-4e50-a6d9-12a29b13967e)

**Comment by errai34** [comment]
yep, i love it! let's go for it

**Comment by jcranney** [comment]
closed with #55
