### ISSUE TITLE
Update website to add John Wu

### ISSUE THREAD

**Issue by errai34** [UniverseTBD/universeTBD.github.io#53]
![jfwu](https://github.com/user-attachments/assets/e4ca3156-fbb8-4ed5-bede-093050466bf5)

John: "John Wu is an Assistant Astronomer at Space Telescope Science Institute (STScI) who primarily studies galaxies with wide-area imaging surveys and machine learning methods like convolutional neural networks and graph neural networks. At STScI, he has advanced strategic initiatives in artificial intelligence and supported the upcoming Roman Space Telescope mission."

**Comment by jcranney** [comment]
closed with #56
