### ISSUE TITLE
[HIGH URGENCY!] Update member participants

### ISSUE THREAD

**Issue by errai34** [UniverseTBD/universeTBD.github.io#58]
Unfortunately, we had Zechang and Josh N leaving UTBD => we should reflect that in their profile. Or to wait until we have Alumni section soon!
We also need to add two new humans:
https://drive.google.com/drive/folders/1zuqdyn1xH1f4Lw2aGO-JP847FVV6AHBu

**Comment by jcranney** [comment]
I propose something like this for now for alumni. Is that suitable @errai34 ?
![image](https://github.com/user-attachments/assets/04a8a0ac-3b6c-42c2-9ced-9411e077eab5)

**Comment by errai34** [comment]
Looks perfect and I think it's fair since Zechang and Josh are PhD researchers and their visibility matters. Let's go for it!

**Comment by errai34** [comment]
On another note, there seems to be some redundancy with Main Participants and Join Us :)). I wonder if we can just show the Main Participants as we hit that button "main participants"

![Screenshot 2024-08-02 at 1 07 27 PM](https://github.com/user-attachments/assets/bb33a3de-bb8e-41af-9b2a-6b6dbc1c021b)

**Comment by jcranney** [comment]
I think I follow, I'll check it out while you go charge your laptop

**Comment by errai34** [comment]
it's still going strong hahahaha... living dangerously
