### ISSUE TITLE
[Relatively high urgency] A few changes to our website to be consistent across platforms:

### ISSUE THREAD

**Issue by errai34** [UniverseTBD/universeTBD.github.io#59]
* What if we bridge Astronomy and Large Language Models to build something truly unique that helps researchers and enthusiasts think deeper about the great beyond? => What if we bridge AI and Science to build something truly unique that helps researchers and enthusiasts think deeper about the great beyond? [just to make it more general]

* Vision: revolutionize -> revolutionise, and there are two dots at the end
Our vision is to revolutionize the way science is done, making the universe of knowledge accessible to all. We aim to be the go-to platform for science benchmarks, data, and reproducible research while fostering a global community of curious minds engaged in groundbreaking research and outreach..
* Values: Transparency, Integrity, Grit, Empowerment, Rigour (TIGER) -> Transparency and Integrity; Junior Leadership -> Junior Empowerment as per our final value doc.
Openness
Excellence with Purpose
Fearless Experimentation
Junior Leadership
Transparency, Integrity, Grit, Empowerment, Rigour (TIGER): FOI we'll use the TIGER internally

* About Us: Jo -> Ioana (Jo). In the last paragraph: steered by  steered by Jo, Maja, Sandor, Kartheik, Mugdha, Pranav and Gabi.
For our next stage, on the funky spaceship steered by Jo, Sandor, Kartheik, we will focus our efforts on open-source and community-led projects. Stay fine-tuned for what's to come.

* Participants: Please change my name to Ioana Ciucă. Australian National University -> Stanford University 
I am an incoming Research Scientist at Stanford University, working at the intersection of Astronomy, Machine Learning and Big Data. I care deeply about education and leveraging high-quality learning resources and mentorship opportunities for students from underrepresented backgrounds. My aim is to champion fearless minds to pursue excellence in service to the world around them. My website is available at: https://www.jociuca.com/.

* About Our Sponsor -> About Our Sponsors

* also something weird with that typed text it keeps getting weird [this is a different issue; seems hard to fix, just thought i'd mention it]

**Comment by jcranney** [comment]
@errai34 can you clarify the third point? What do you want the item to be changed to?

**Comment by errai34** [comment]
Transparency, Integrity, Grit, Empowerment, Rigour (TIGER) -> Transparency and Integrity

**Comment by errai34** [comment]
gotta trim a bit :D

**Comment by jcranney** [comment]
The last point was pointed out by jayden in #44, we don't have a fix yet except for disable the nice feature. Since that part of this issue is redundant, I will close this issue when all the other issues are fixed
