### ISSUE TITLE
[High Urgency] Update Research and products 

### ISSUE THREAD

**Issue by errai34** [UniverseTBD/universeTBD.github.io#60]
We want to update this part: https://universetbd.org/products and the research part

* Pathfinder: https://pfdr.app
the description: Pathfinder is an AI tool designed to enable literature review and knowledge discovery in astronomy, utilising state-of-the-art large language models and a corpus of 350,000 peer-reviewed papers from the Astrophysics Data System. It focuses on semantic searching with natural language instead of syntactic searches with keywords, offering an innovative approach to scientific enquiry and literature exploration in the face of exponentially growing astronomical literature.

* AstroPT is an autoregressive pretrained transformer developed for astronomical use-cases, trained on 8.6 million galaxy postage stamp observations from the DESI Legacy Survey DR8. The project aims to create an open-source "Large Observation Model" for observational sciences, with models ranging from 1 million to 2.1 billion parameters showing improved performance on downstream tasks as model size increases. @Smith42 can you check, also can you provide a logo :d?

* we can keep the steering of charlie there 
* we can also keep Hypothesis Generation there

For the Research we need to put astrollama-chat and astropt papers

**Comment by Smith42** [comment]
Maybe this blurb for astroPT?

AstroPT is an autoregressive pretrained transformer developed for astronomical use-cases. V1.0 has been trained on 8.6 million galaxy postage stamp observations from the DESI Legacy Survey DR8 with models ranging from 1 million to 2.1 billion parameters. Just like for LLMs, we see improved performance on downstream tasks as model size increases. The project's north star is integrating many astronomical modalities from imagery to stellar time series to spectra to hyperspectral cubes, with the end goal of creating an open-source "Large Observation Model" for observational sciences.

There's a mascot here: https://github.com/Smith42/astroPT/blob/main/assets/emoji.png

**Comment by Smith42** [comment]
AstroPT paper is here https://arxiv.org/abs/2405.14930v1

**Comment by jcranney** [comment]
I've added the astrollama-chat and astropt papers to the Research page, and astropt to the products page, but I think the summary needs to be much shorter for the products page - one sentence. I propose something like:
"AstroPT is an autoregressive pretrained transformer developed for astronomical use-cases, and V1.0 has been trained on 8.6 million galaxy postage stamp observations from the DESI Legacy Survey DR8."

**Comment by Smith42** [comment]
Hmm maybe this as a one sentencer?

AstroPT is an AI model designed for astronomical applications, trained on millions of galaxy images, with plans to incorporate diverse astronomical data types to create a comprehensive "Large Observation Model" for astronomy.

**Comment by jcranney** [comment]
I'll merge what has been fixed so far, but I haven't done anything about https://pfdr.app
If someone can provide a square logo and a one-sentencer, then I'll add it to the products page.

**Comment by errai34** [comment]
For Pathfinder [a temp one while Kartheik makes the final version, but in time for the release]:
![pfdr](https://github.com/user-attachments/assets/34e8e014-e57c-48ac-862f-2306abe1af40)

The blurb: Pathfinder is an AI framework designed for astronomical literature review and knowledge discovery, using more than 300,000 peer-reviewed papers from the Astrophysics Data System. It incorporates advanced retrieval techniques and large language models to enable semantic searching of astronomy literature. 

@kartheikiyer , hope this all good!

**Comment by errai34** [comment]
For the Highlights, we probs want to keep Pathfinder, AstroPT and Hypothesis Gen in order of release :-)

**Comment by errai34** [comment]
@Smith42 you also made some really nice squares, maybe we can choose between all of these and let jesse decide haha?

**Comment by errai34** [comment]
![photo](https://github.com/user-attachments/assets/bb65af6e-6beb-4ce0-ba40-acad38c697e2)
entry from Michele too

**Comment by errai34** [comment]
think the owl one is the winner :D

**Comment by Smith42** [comment]
Yeah I quite like the owl one

**Comment by errai34** [comment]
I think it's back, so we can merge <3. Thanks Jesse!
