### ISSUE TITLE
[HIGH URGENCY] A few Pages of UTBD need some updates 

### ISSUE THREAD

**Issue by errai34** [UniverseTBD/universeTBD.github.io#61]
![Screenshot 2024-08-02 at 12 34 50 PM](https://github.com/user-attachments/assets/5dcc6e23-cb62-47db-8f25-6a7ccad881df)

500,000+
Research Papers
We are actively developing models and benchmarks to explore and harness this vast literature 

A diverse team of over 30 scientists, techies, artists and enthusiasts from around the world

Products: 5->8
We’ve achieved significant advancements and are enthusiastically pushing forward for more

* Also in the joinus: 
https://universetbd.org/people/joinus: machine learning enthusiasts -> researchers
We are a group of scientists, machine learning researchers, engineers, and enthusiasts, eminently human from all over the world, united to achieve our shared vision.

![Screenshot 2024-08-02 at 12 50 20 PM](https://github.com/user-attachments/assets/6b132745-3697-4923-a3f5-9fb335ea2805)

* Here I was wondering if we could add: If you want to support us in our mission, please reach out to exec@universetbd.org.

* also the socials logos aren't showing

**Comment by jcranney** [comment]
What about we change "Join Us" to "Contact" in the navbar at the top, then the page is something like this
![image](https://github.com/user-attachments/assets/61ec2186-0451-4fa6-b162-ebd54159804a)

**Comment by jcranney** [comment]
Also sorry for living under a rock but do we want the twitter bird or the "X" logo, either is possible @errai34
