### ISSUE TITLE
Adding Rish to website

### ISSUE THREAD

**Issue by errai34** [UniverseTBD/universeTBD.github.io#72]
The info is here: https://drive.google.com/drive/folders/1zuqdyn1xH1f4Lw2aGO-JP847FVV6AHBu?usp=sharing

**Comment by rishistyping** [comment]
```
Thank you!!!
```

**Comment by rishistyping** [comment]
Bumping this up @errai34

**Comment by errai34** [comment]
@jcranney @jayden626 <3

**Comment by jcranney** [comment]
sorry, I missed this! done now :)
