### ISSUE TITLE
Adding MMU blogpost to prep for release 

### ISSUE THREAD

**Issue by errai34** [UniverseTBD/universeTBD.github.io#76]
@Smith42 @jcranney what do we need to add here in prep for the release

**Comment by jcranney** [comment]
I guess we want something to show on the [products page](https://universetbd.org/products) and perhaps a paper for our [research page](https://universetbd.org/research).

For the product, we need:
- image,
- title (1 or 2 words),
- description (<50 words),
- url for more info,

For the paper (if applicable), we need:
- title,
- date,
- authors,
- arxiv ID,
- abstract,

**Comment by Smith42** [comment]
Yep let me write some copy here:

Product:

image: https://github.com/MultimodalUniverse/MultimodalUniverse/blob/main/assets/multimodal_universe.png
title: Multimodal Universe
description: The Multimodal Universe (MMU) is a huge 100TB dataset bringing together the largest collection of astronomical observations ever assembled to accelerate open AI and astronomy research. Think ImageNet, but for space 🚀.
url: https://github.com/MultimodalUniverse/MultimodalUniverse/tree/main, https://huggingface.co/MultimodalUniverse, https://openreview.net/forum?id=EWm9zR5Qy1#discussion

Paper:

title: The Multimodal Universe: Enabling Large-Scale Machine Learning with 100 TB of Astronomical Scientific Data
date: 13 Nov 2024
authors: The Multimodal Universe Collaboration
abstract: We present the Multimodal Universe, a large-scale multimodal dataset of scientific astronomical data, compiled specifically to facilitate machine learning research. Overall, our dataset contains hundreds of millions of astronomical observations, constituting 100TB of multi-channel and hyper-spectral images, spectra, multivariate time series, as well as a wide variety of associated scientific measurements and metadata. In addition, we include a range of benchmark tasks representative of standard practices for machine learning methods in astrophysics. This massive dataset will enable the development of large multi-modal models specifically targeted towards scientific applications. All codes used to compile the dataset, and a description of how to access the data is available at https://github.com/MultimodalUniverse/MultimodalUniverse
